import { Routine, Checklist, Backpack, UserSettings, TemplateItem, Activity, BackpackItem } from '../types';

export type { TemplateItem };

export const PREPROGRAMMED_ACTIVITIES: Omit<Activity, 'id' | 'completed'>[] = [
  { name: 'Brush teeth', emoji: '🪥', color: '#38bdf8', durationMinutes: 3, isLowEnergy: true },
  { name: 'Drink water', emoji: '💧', color: '#0ea5e9', durationMinutes: 1, isLowEnergy: true },
  { name: 'Wash face / Skincare', emoji: '✨', color: '#f472b6', durationMinutes: 5, isLowEnergy: false },
  { name: 'Take medication / Vitamins', emoji: '💊', color: '#a855f7', durationMinutes: 1, isLowEnergy: true },
  { name: 'Shower', emoji: '🚿', color: '#06b6d4', durationMinutes: 12, isLowEnergy: false },
  { name: 'Get dressed', emoji: '👕', color: '#f97316', durationMinutes: 5, isLowEnergy: true },
  { name: 'Eat breakfast', emoji: '🥣', color: '#eab308', durationMinutes: 15, isLowEnergy: false },
  { name: 'Make bed', emoji: '🛏️', color: '#84cc16', durationMinutes: 2, isLowEnergy: true },
  { name: 'Pack backpack / bag', emoji: '🎒', color: '#6366f1', durationMinutes: 4, isLowEnergy: true },
  { name: 'Stretch / Gentle movement', emoji: '🧘', color: '#10b981', durationMinutes: 7, isLowEnergy: false },
  { name: 'Exercise / Workout', emoji: '🏃', color: '#ef4444', durationMinutes: 25, isLowEnergy: false },
  { name: 'Clean room / Tidy up', emoji: '🧹', color: '#ec4899', durationMinutes: 10, isLowEnergy: false },
  { name: 'Leave for work / school', emoji: '🚶', color: '#f43f5e', durationMinutes: 2, isLowEnergy: true },
  { name: 'Study / Focus session', emoji: '📚', color: '#8b5cf6', durationMinutes: 30, isLowEnergy: false },
  { name: 'Put away phone', emoji: '📵', color: '#64748b', durationMinutes: 1, isLowEnergy: true },
  { name: 'Go to sleep', emoji: '😴', color: '#475569', durationMinutes: 10, isLowEnergy: true },
];

export const PREPROGRAMMED_BACKPACK_ITEMS: Omit<BackpackItem, 'id' | 'isPacked'>[] = [
  { name: 'Phone', emoji: '📱', color: '#38bdf8', isRequired: true, quantity: 1 },
  { name: 'Wallet / Cards', emoji: '👛', color: '#eab308', isRequired: true, quantity: 1 },
  { name: 'Keys', emoji: '🔑', color: '#f59e0b', isRequired: true, quantity: 1 },
  { name: 'Charger & Cable', emoji: '🔌', color: '#6366f1', isRequired: true, quantity: 1 },
  { name: 'Water bottle', emoji: '💧', color: '#06b6d4', isRequired: true, quantity: 1 },
  { name: 'Headphones / Earbuds', emoji: '🎧', color: '#ec4899', isRequired: false, quantity: 1 },
  { name: 'Laptop', emoji: '💻', color: '#64748b', isRequired: false, quantity: 1 },
  { name: 'Notebook & Pens', emoji: '📓', color: '#10b981', isRequired: false, quantity: 1 },
  { name: 'ID / Transit Pass', emoji: '🪪', color: '#8b5cf6', isRequired: true, quantity: 1 },
  { name: 'Medication', emoji: '💊', color: '#ef4444', isRequired: true, quantity: 1 },
  { name: 'Gym clothes & sneakers', emoji: '👟', color: '#f97316', isRequired: false, quantity: 1 },
  { name: 'Toiletries / Lip balm', emoji: '🧴', color: '#f472b6', isRequired: false, quantity: 1 },
  { name: 'Snack / Energy bar', emoji: '🍎', color: '#84cc16', isRequired: false, quantity: 2 },
];

export const DEFAULT_USER_SETTINGS: UserSettings = {
  firstName: 'Friend',
  theme: 'pastel',
  fontSize: 'normal',
  layoutDensity: 'comfortable',
  soundsEnabled: true,
  soundEnabled: true,
  vibrationEnabled: true,
  hapticsEnabled: true,
  completionConfetti: true,
  countdownDuration: 5,
  defaultCountdownDuration: 5,
  countdownSound: true,
  countdownVibrate: true,
  countdownAutoStart: true,
  countdownTiming: 'before_task',
  notificationsEnabled: true,
  notificationQuietHoursStart: '22:00',
  notificationQuietHoursEnd: '07:00',
  reminderSound: true,
  dailySummaryEnabled: true,
  isLowEnergyMode: false,
  journalReminderEnabled: false,
  journalReminderTimeSlot: 'evening',
  journalReminderCustomTime: '20:30',
};

export const JOURNAL_MOODS: { id: import('../types').JournalMood; label: string; emoji: string; color: string }[] = [
  { id: 'happy', label: 'Happy', emoji: '😊', color: '#f59e0b' },
  { id: 'sad', label: 'Sad', emoji: '😔', color: '#3b82f6' },
  { id: 'anxious', label: 'Anxious', emoji: '😟', color: '#8b5cf6' },
  { id: 'calm', label: 'Calm', emoji: '😌', color: '#10b981' },
  { id: 'excited', label: 'Excited', emoji: '🤩', color: '#ec4899' },
  { id: 'tired', label: 'Tired', emoji: '😴', color: '#64748b' },
  { id: 'angry', label: 'Angry', emoji: '😡', color: '#ef4444' },
  { id: 'grateful', label: 'Grateful', emoji: '🥹', color: '#06b6d4' },
  { id: 'motivated', label: 'Motivated', emoji: '🔥', color: '#ea580c' },
  { id: 'neutral', label: 'Neutral', emoji: '😐', color: '#78716c' },
];

export const DEFAULT_ROUTINES: Routine[] = [
  {
    id: 'routine-morning-full',
    name: 'Morning Routine',
    emoji: '☀️',
    color: '#f59e0b',
    description: 'Start the day grounded with gentle hydration and hygiene.',
    versionName: 'Full Version',
    isArchived: false,
    isMorningRoutine: true,
    estimatedDuration: 26,
    linkedBackpackId: 'backpack-work',
    createdAt: new Date().toISOString(),
    recurring: {
      frequency: 'daily',
      time: '07:30',
      startDate: new Date().toISOString().split('T')[0],
    },
    activities: [
      { id: 'act-1', name: 'Drink a glass of water', emoji: '💧', color: '#0ea5e9', durationMinutes: 1, completed: false, isLowEnergy: true },
      { id: 'act-2', name: 'Wash face & Skincare', emoji: '✨', color: '#ec4899', durationMinutes: 5, completed: false, isLowEnergy: false },
      { id: 'act-3', name: 'Brush teeth', emoji: '🪥', color: '#38bdf8', durationMinutes: 3, completed: false, isLowEnergy: true },
      { id: 'act-4', name: 'Take morning vitamins', emoji: '💊', color: '#a855f7', durationMinutes: 1, completed: false, isLowEnergy: true },
      { id: 'act-5', name: 'Get dressed into comfortable clothes', emoji: '👕', color: '#f97316', durationMinutes: 4, completed: false, isLowEnergy: true },
      { id: 'act-6', name: 'Eat a nourishing breakfast', emoji: '🥣', color: '#eab308', durationMinutes: 10, completed: false, isLowEnergy: false },
      { id: 'act-7', name: 'Check backpack for daily essentials', emoji: '🎒', color: '#6366f1', durationMinutes: 2, completed: false, isLowEnergy: true },
    ],
  },
  {
    id: 'routine-morning-quick',
    name: 'Quick Morning (Low Energy)',
    emoji: '🌱',
    color: '#10b981',
    description: 'A gentle, zero-pressure 3-step routine for tough or tired mornings.',
    versionName: 'Low Energy',
    isArchived: false,
    isMorningRoutine: true,
    estimatedDuration: 6,
    linkedBackpackId: 'backpack-work',
    createdAt: new Date().toISOString(),
    activities: [
      { id: 'act-q1', name: 'Drink water', emoji: '💧', color: '#0ea5e9', durationMinutes: 1, completed: false, isLowEnergy: true },
      { id: 'act-q2', name: 'Brush teeth', emoji: '🪥', color: '#38bdf8', durationMinutes: 2, completed: false, isLowEnergy: true },
      { id: 'act-q3', name: 'Slip into clean clothes', emoji: '👕', color: '#f97316', durationMinutes: 3, completed: false, isLowEnergy: true },
    ],
  },
  {
    id: 'routine-evening-winddown',
    name: 'Evening Wind Down',
    emoji: '🌙',
    color: '#8b5cf6',
    description: 'Calm the mind, dim the lights, and prepare for restful sleep.',
    versionName: 'Full Version',
    isArchived: false,
    isMorningRoutine: false,
    estimatedDuration: 18,
    createdAt: new Date().toISOString(),
    recurring: {
      frequency: 'daily',
      time: '21:30',
      startDate: new Date().toISOString().split('T')[0],
    },
    activities: [
      { id: 'act-e1', name: 'Plug phone in away from bed', emoji: '🔌', color: '#6366f1', durationMinutes: 1, completed: false, isLowEnergy: true },
      { id: 'act-e2', name: 'Pack backpack for tomorrow', emoji: '🎒', color: '#f59e0b', durationMinutes: 4, completed: false, isLowEnergy: true },
      { id: 'act-e3', name: 'Brush teeth & floss', emoji: '🪥', color: '#38bdf8', durationMinutes: 3, completed: false, isLowEnergy: true },
      { id: 'act-e4', name: '5 minutes of quiet reading or stretching', emoji: '📖', color: '#10b981', durationMinutes: 5, completed: false, isLowEnergy: true },
      { id: 'act-e5', name: 'Lights out & sleep', emoji: '😴', color: '#475569', durationMinutes: 5, completed: false, isLowEnergy: true },
    ],
  },
];

export const DEFAULT_CHECKLISTS: Checklist[] = [
  {
    id: 'chk-selfcare',
    name: 'Daily Self-Care Nudges',
    emoji: '🌿',
    color: '#10b981',
    description: 'Gentle check-ins with your body and mind throughout the day.',
    isArchived: false,
    createdAt: new Date().toISOString(),
    items: [
      { id: 'item-1', title: 'Take 3 deep grounding breaths', completed: false, emoji: '💨', color: '#10b981' },
      { id: 'item-2', title: 'Drink at least 3 glasses of water', completed: false, emoji: '💧', color: '#0ea5e9' },
      { id: 'item-3', title: 'Step outside or open a window for fresh air', completed: false, emoji: '☀️', color: '#f59e0b' },
      { id: 'item-4', title: 'Eat something satisfying', completed: false, emoji: '🥪', color: '#f97316' },
      { id: 'item-5', title: 'Say one kind thought to yourself', completed: false, emoji: '💛', color: '#eab308' },
    ],
  },
  {
    id: 'chk-grocery',
    name: 'Grocery & Snacks',
    emoji: '🛒',
    color: '#f97316',
    description: 'Keep your pantry stocked with simple comfort foods.',
    isArchived: false,
    createdAt: new Date().toISOString(),
    items: [
      { id: 'item-g1', title: 'Fresh fruit (bananas / berries)', completed: false, emoji: '🍌', color: '#eab308' },
      { id: 'item-g2', title: 'Oat milk or favorite dairy', completed: false, emoji: '🥛', color: '#38bdf8' },
      { id: 'item-g3', title: 'Bread or bagels', completed: false, emoji: '🍞', color: '#f59e0b' },
      { id: 'item-g4', title: 'Peanut butter or jam', completed: false, emoji: '🥜', color: '#d97706' },
      { id: 'item-g5', title: 'Quick frozen veggies or meal', completed: false, emoji: '🥦', color: '#10b981' },
    ],
  },
];

export const DEFAULT_BACKPACKS: Backpack[] = [
  {
    id: 'backpack-work',
    name: 'Everyday Work / School Backpack',
    emoji: '🎒',
    color: '#6366f1',
    description: 'Never leave behind keys, chargers, or your badge again.',
    isArchived: false,
    packForTomorrow: true,
    lastPackedAt: undefined,
    associatedRoutineId: 'routine-morning-full',
    createdAt: new Date().toISOString(),
    items: [
      { id: 'bp-1', name: 'Keys (House & Car)', emoji: '🔑', color: '#f59e0b', quantity: 1, isRequired: true, isPacked: false },
      { id: 'bp-2', name: 'Wallet & Transit Card', emoji: '👛', color: '#eab308', quantity: 1, isRequired: true, isPacked: false },
      { id: 'bp-3', name: 'Phone & Charging Cable', emoji: '📱', color: '#38bdf8', quantity: 1, isRequired: true, isPacked: false },
      { id: 'bp-4', name: 'Laptop & Charger block', emoji: '💻', color: '#6366f1', quantity: 1, isRequired: true, isPacked: false },
      { id: 'bp-5', name: 'Water Bottle', emoji: '💧', color: '#06b6d4', quantity: 1, isRequired: true, isPacked: false },
      { id: 'bp-6', name: 'Headphones / Earbuds', emoji: '🎧', color: '#ec4899', quantity: 1, isRequired: false, isPacked: false },
      { id: 'bp-7', name: 'Lip Balm / Mints', emoji: '🧴', color: '#f472b6', quantity: 1, isRequired: false, isPacked: false },
    ],
  },
  {
    id: 'backpack-gym',
    name: 'Gym & Movement Bag',
    emoji: '👟',
    color: '#ef4444',
    description: 'Ready to grab when you want to get moving.',
    isArchived: false,
    createdAt: new Date().toISOString(),
    items: [
      { id: 'bg-1', name: 'Gym clothes & clean socks', emoji: '👕', color: '#f97316', quantity: 1, isRequired: true, isPacked: false },
      { id: 'bg-2', name: 'Sneakers', emoji: '👟', color: '#ef4444', quantity: 1, isRequired: true, isPacked: false },
      { id: 'bg-3', name: 'Workout water bottle', emoji: '💧', color: '#06b6d4', quantity: 1, isRequired: true, isPacked: false },
      { id: 'bg-4', name: 'Gym lock & key', emoji: '🔒', color: '#64748b', quantity: 1, isRequired: true, isPacked: false },
      { id: 'bg-5', name: 'Small sweat towel', emoji: '🧖', color: '#10b981', quantity: 1, isRequired: false, isPacked: false },
    ],
  },
];

export const TEMPLATE_LIBRARY: TemplateItem[] = [
  {
    id: 'tmpl-morning-gentle',
    type: 'routine',
    category: 'Morning routines',
    name: 'Gentle Awakening Routine',
    emoji: '🌅',
    color: '#f59e0b',
    description: 'A soothing, low-stress morning sequence to greet the day slowly.',
    data: {
      name: 'Gentle Awakening Routine',
      emoji: '🌅',
      color: '#f59e0b',
      isMorningRoutine: true,
      estimatedDuration: 20,
      activities: [
        { id: 't-1', name: 'Drink tall glass of warm water', emoji: '💧', color: '#0ea5e9', durationMinutes: 2, completed: false, isLowEnergy: true },
        { id: 't-2', name: '5 gentle bed stretches', emoji: '🧘', color: '#10b981', durationMinutes: 5, completed: false, isLowEnergy: true },
        { id: 't-3', name: 'Wash face with cool water', emoji: '✨', color: '#ec4899', durationMinutes: 3, completed: false, isLowEnergy: true },
        { id: 't-4', name: 'Brush teeth & rinse', emoji: '🪥', color: '#38bdf8', durationMinutes: 3, completed: false, isLowEnergy: true },
        { id: 't-5', name: 'Cozy breakfast & tea', emoji: '🍵', color: '#eab308', durationMinutes: 7, completed: false, isLowEnergy: false },
      ],
    },
  },
  {
    id: 'tmpl-study-focus',
    type: 'routine',
    category: 'Study plans',
    name: 'Study / Focus Jumpstart',
    emoji: '🧠',
    color: '#8b5cf6',
    description: 'Beat task initiation resistance before a big work or study sprint.',
    data: {
      name: 'Study / Focus Jumpstart',
      emoji: '🧠',
      color: '#8b5cf6',
      isMorningRoutine: false,
      estimatedDuration: 15,
      activities: [
        { id: 'ts-1', name: 'Clear desk of everything except notebooks', emoji: '🧹', color: '#ec4899', durationMinutes: 3, completed: false, isLowEnergy: true },
        { id: 'ts-2', name: 'Fill water cup & grab a healthy snack', emoji: '🍎', color: '#10b981', durationMinutes: 2, completed: false, isLowEnergy: true },
        { id: 'ts-3', name: 'Put phone in Do Not Disturb', emoji: '📵', color: '#64748b', durationMinutes: 1, completed: false, isLowEnergy: true },
        { id: 'ts-4', name: 'Pick the FIRST smallest micro-task', emoji: '🎯', color: '#f97316', durationMinutes: 2, completed: false, isLowEnergy: true },
        { id: 'ts-5', name: '5-second countdown & start 25m sprint', emoji: '🚀', color: '#6366f1', durationMinutes: 5, completed: false, isLowEnergy: true },
      ],
    },
  },
  {
    id: 'tmpl-cleaning-reset',
    type: 'checklist',
    category: 'Cleaning checklists',
    name: '15-Minute Room Reset',
    emoji: '🧹',
    color: '#06b6d4',
    description: 'Zero overwhelm quick reset for living room or bedroom.',
    data: {
      name: '15-Minute Room Reset',
      emoji: '🧹',
      color: '#06b6d4',
      items: [
        { id: 'tc-1', title: 'Collect all empty cups and dishes to the sink', completed: false, emoji: '☕', color: '#0ea5e9' },
        { id: 'tc-2', title: 'Toss obvious trash & wrappers in the bin', completed: false, emoji: '🗑️', color: '#ef4444' },
        { id: 'tc-3', title: 'Put dirty clothes into the hamper', completed: false, emoji: '🧺', color: '#8b5cf6' },
        { id: 'tc-4', title: 'Pull blanket over the bed so it looks neat', completed: false, emoji: '🛏️', color: '#10b981' },
        { id: 'tc-5', title: 'Wipe desk with a moist cloth', completed: false, emoji: '✨', color: '#f59e0b' },
      ],
    },
  },
  {
    id: 'tmpl-travel-bag',
    type: 'backpack',
    category: 'Travel packing lists',
    name: 'Weekend Trip Carry-On',
    emoji: '✈️',
    color: '#ec4899',
    description: 'Essential packing list for 2-3 day getaways so you leave stress behind.',
    data: {
      name: 'Weekend Trip Carry-On',
      emoji: '✈️',
      color: '#ec4899',
      items: [
        { id: 'tb-1', name: 'ID / Passport / Boarding documents', emoji: '🪪', color: '#6366f1', quantity: 1, isRequired: true, isPacked: false },
        { id: 'tb-2', name: 'Prescription Medication', emoji: '💊', color: '#ef4444', quantity: 1, isRequired: true, isPacked: false },
        { id: 'tb-3', name: 'Phone charger & portable power bank', emoji: '🔋', color: '#10b981', quantity: 1, isRequired: true, isPacked: false },
        { id: 'tb-4', name: '3 pairs of underwear & socks', emoji: '🧦', color: '#f97316', quantity: 3, isRequired: true, isPacked: false },
        { id: 'tb-5', name: 'Toiletry kit with travel toothbrush', emoji: '🪥', color: '#06b6d4', quantity: 1, isRequired: true, isPacked: false },
        { id: 'tb-6', name: 'Comfortable walking shoes', emoji: '👟', color: '#eab308', quantity: 1, isRequired: false, isPacked: false },
      ],
    },
  },
  {
    id: 'tmpl-selfcare-plan',
    type: 'checklist',
    category: 'Self-care plans',
    name: 'Low Spoon / Overwhelm Day Care',
    emoji: '🧸',
    color: '#ec4899',
    description: 'Compassionate essentials when energy is very low. No guilt.',
    data: {
      name: 'Low Spoon / Overwhelm Day Care',
      emoji: '🧸',
      color: '#ec4899',
      items: [
        { id: 'ls-1', title: 'Forgive yourself for feeling exhausted today', completed: false, emoji: '💛', color: '#eab308' },
        { id: 'ls-2', title: 'Drink a sip of water or favorite tea', completed: false, emoji: '💧', color: '#0ea5e9' },
        { id: 'ls-3', title: 'Eat whatever simple food is easiest to access', completed: false, emoji: '🥪', color: '#f97316' },
        { id: 'ls-4', title: 'Put on clean, soft socks or warm sweater', completed: false, emoji: '🧦', color: '#8b5cf6' },
        { id: 'ls-5', title: 'Switch phone to do-not-disturb', completed: false, emoji: '🌙', color: '#64748b' },
      ],
    },
  },
];

export interface ThemeConfig {
  id: string;
  name: string;
  description: string;
  isDark: boolean;
  bgMain: string;
  bgCard: string;
  bgCardHover: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  border: string;
  accent: string;
  accentSubtle: string;
  accentText: string;
}

export const THEMES: Record<string, ThemeConfig> = {
  pastel: {
    id: 'pastel',
    name: 'Soft Pastel',
    description: 'Warm cream, gentle blush, and soothing lavender',
    isDark: false,
    bgMain: '#faf7f2',
    bgCard: '#ffffff',
    bgCardHover: '#fdfbf7',
    textPrimary: '#292524',
    textSecondary: '#57534e',
    textMuted: '#a8a29e',
    border: '#f0ece1',
    accent: '#f59e0b',
    accentSubtle: '#fef3c7',
    accentText: '#92400e',
  },
  dark: {
    id: 'dark',
    name: 'Dark Cozy',
    description: 'Deep slate with gentle warm glowing elements',
    isDark: true,
    bgMain: '#0f172a',
    bgCard: '#1e293b',
    bgCardHover: '#334155',
    textPrimary: '#f8fafc',
    textSecondary: '#cbd5e1',
    textMuted: '#64748b',
    border: '#334155',
    accent: '#38bdf8',
    accentSubtle: '#0369a1',
    accentText: '#e0f2fe',
  },
  retro: {
    id: 'retro',
    name: 'Retro Sunset',
    description: 'Warm terracotta, amber glow, and vintage paper tone',
    isDark: false,
    bgMain: '#fef3c7',
    bgCard: '#ffffff',
    bgCardHover: '#fffbeb',
    textPrimary: '#451a03',
    textSecondary: '#78350f',
    textMuted: '#b45309',
    border: '#fde68a',
    accent: '#ea580c',
    accentSubtle: '#ffedd5',
    accentText: '#9a3412',
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal Clean',
    description: 'Refined off-white, calm grays, and precise spacing',
    isDark: false,
    bgMain: '#f8fafc',
    bgCard: '#ffffff',
    bgCardHover: '#f1f5f9',
    textPrimary: '#0f172a',
    textSecondary: '#475569',
    textMuted: '#94a3b8',
    border: '#e2e8f0',
    accent: '#475569',
    accentSubtle: '#f1f5f9',
    accentText: '#0f172a',
  },
  nature: {
    id: 'nature',
    name: 'Nature Calm',
    description: 'Sage foliage, tranquil earth, and forest morning vibes',
    isDark: false,
    bgMain: '#f0fdf4',
    bgCard: '#ffffff',
    bgCardHover: '#f7fee7',
    textPrimary: '#14532d',
    textSecondary: '#166534',
    textMuted: '#4ade80',
    border: '#dcfce7',
    accent: '#15803d',
    accentSubtle: '#dcfce7',
    accentText: '#14532d',
  },
  y2k: {
    id: 'y2k',
    name: 'Y2K Vibrant',
    description: 'Playful lavender, bubblegum pink, and electric energy',
    isDark: false,
    bgMain: '#faf5ff',
    bgCard: '#ffffff',
    bgCardHover: '#fdf4ff',
    textPrimary: '#581c87',
    textSecondary: '#7e22ce',
    textMuted: '#c084fc',
    border: '#f3e8ff',
    accent: '#c026d3',
    accentSubtle: '#fae8ff',
    accentText: '#86198f',
  },
  monochrome: {
    id: 'monochrome',
    name: 'Monochrome Ink',
    description: 'Classic high contrast ink and pristine paper',
    isDark: false,
    bgMain: '#f5f5f4',
    bgCard: '#ffffff',
    bgCardHover: '#fafaf9',
    textPrimary: '#1c1917',
    textSecondary: '#44403c',
    textMuted: '#78716c',
    border: '#e7e5e4',
    accent: '#292524',
    accentSubtle: '#e7e5e4',
    accentText: '#1c1917',
  },
};
